/* tslint:disable */
/* eslint-disable */
/**
 * LeftOverLove.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerDto
 */
export interface CustomerDto {
    /**
     * 
     * @type {number}
     * @memberof CustomerDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerDto
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDto
     */
    lastName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerDto
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerDto
     */
    points?: number;
}

/**
 * Check if a given object implements the CustomerDto interface.
 */
export function instanceOfCustomerDto(value: object): value is CustomerDto {
    return true;
}

export function CustomerDtoFromJSON(json: any): CustomerDto {
    return CustomerDtoFromJSONTyped(json, false);
}

export function CustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'points': json['points'] == null ? undefined : json['points'],
    };
}

export function CustomerDtoToJSON(value?: CustomerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'longitude': value['longitude'],
        'latitude': value['latitude'],
        'points': value['points'],
    };
}

